### PR TITLE
Feature branch

### PR DESCRIPTION
**Pull request by chindrop**
## Enumerable Methods.

In this project:
- I re-built the enumerable methods

### CODE REVIEW

**Comment by lekegitrepo** [comment]
#### Hi @chindrop :clap: :clap:
##### Well done so far. However, there are a few issues you need to fix before this project can be approved.

**_1. Fix the Stickler errors_**

**_2. Fix the implementation of the my_map method to handle this test case:_**
 ` (1..4).map { |n| n * n }`

**_3. Fix the implementation of the my_each_with_index method:_**
 - `(1..5).each_with_index { |element, index| puts "#{element} => #{index}" }`
**_should return:_**
  **_1 => 0
  2 => 1
  3 => 2
  4 => 3
  5 => 4_**

 - `[1, 2, 3, 4, 5].each_with_index { |element, index| puts "#{element} => #{index}" }`
**_should return:_**
**_1 => 0
2 => 1
3 => 2
4 => 3
5 => 4_**

**_4. Remove the 'end' on line 143 of the enumerables.rb file_**

**_Optional_**
- **_Move the multiply_els method out of the enumerable module i.e define it outside._**

_**implement these changes and submit for review.**_

### _Reviewed by Temitayo Adeleke._

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
#### Status: Request changes

**Review by mosesogwo — CHANGES_REQUESTED** [review]
**Hi @chindrop, impressive work so far :+1:, but we still have some bugs to be fixed:**
:point_right: This was pointed out in the last review. When a block is given to **my_each_with_index**, it should call the block for each element and it's index... so 
`[1, 2, 3, 4, 5].my_each_with_index { |element, index| puts "#{element} => #{index}" }`
should print
```ruby
1 => 0
2 => 1
3 => 2
4 => 3
5 => 4
```
instead of 

```ruby
1 => 
2 => 
3 => 
4 => 
5 => 
```
Try to figure out why the index is not passed and fix it.

:point_right: When **my_each_with_index** is called on a range, your method throws an error because of the use of the length method which cannot be called on the range... You can try converting the range to an array before calling length on it.

:point_right: When **my_each_with_index** is called on a hash, your method doesn't return the correct output.
`{ a: 1, b: 2, c: 3, d: 4, e: 5 }.my_each_with_index { |ele, idx| puts "#{ele}" => "#{idx}"}`
prints 
```ruby
{""=>""}
{""=>""}
{""=>""}
{""=>""}
{""=>""}
```
instead of:
```ruby
{"[:a, 1]"=>"0"}
{"[:b, 2]"=>"1"}
{"[:c, 3]"=>"2"}
{"[:d, 4]"=>"3"}
{"[:e, 5]"=>"4"}
```
:point_right: When both a block and proc are given to **my_map**, it should return a new array with the result of running the proc (not the block) once for each element. Your current my_map cannot take a proc as argument. You should fix this. You can see [this article](https://blog.appsignal.com/2018/09/04/ruby-magic-closures-in-ruby-blocks-procs-and-lambdas.html) that shows how to pass a proc as argument.


_**Kindly make these changes and submit another code review request.**_

**Any questions? You can reach me on Slack (Moses Ogwo)**

**Cheers:stars:**

### Status: Changes Requested.

**Review by rOluochKe — APPROVED** [review]
Hello Team!
### Congratulations :boom: :100: You got it right this time. The project has been approved.
### Merge and submit the project. Good luck with the next project.
- Happy coding!

**Pull request merged**
